### ISSUE TITLE
"vpm" field in registry.json

### ISSUE THREAD

**Issue by vulpivia** [vpkg-project/registry#6]
Is the "vpm" field for a package in registry.json required? The README doesn't mention it, but every package has it.

**Comment by nedpals** [comment]
Forgot to update it but it is required. This is just to track every package just in case vpm is down.

**Comment by vulpivia** [comment]
Isn't vpkg independent of vpm?

**Comment by nedpals** [comment]
Yes, but it does not mean that by being "independent" we are not allowed to be a mirror registry that is compatible with the protocols vpm uses.

**Comment by vulpivia** [comment]
From going over the source code, it seems to me that vpm is a source if a package is not a git repository, is that right? Maybe I don't really understand the relationship between vpkg and vpm.

Is it possible to add a package to vpkg without adding it to vpm?

**Comment by nedpals** [comment]
> From going over the source code, it seems to me that vpm is a source if a package is not a git repository, is that right?

Yes. It's more of like an alias that you can use if you are getting used to doing the `v install username.package` style.

> Maybe I don't really understand the relationship between vpkg and vpm.

vpkg is a third-party package manager for V. While vpm is the official package manager maintained by the core team.

> Is it possible to add a package to vpkg without adding it to vpm?

Yes you can. You can simply add `"vpm": ""` if you haven't published your module to VPM yet.

**Comment by vulpivia** [comment]
Alright, now I get it. Thank you :smiley:
